In [2]:
%pip install pyodbc
%pip install python-dotenv

Requirement already satisfied: pyodbc in c:\users\ofori\appdata\local\programs\python\python310\lib\site-packages (5.0.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: python-dotenv in c:\users\ofori\appdata\local\programs\python\python310\lib\site-packages (1.0.0)Note: you may need to restart the kernel to use updated packages.

In [3]:
import pyodbc 
from dotenv import dotenv_values
import pandas as pd
import warnings 

warnings.filterwarnings('ignore')

In [4]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')

In [5]:
# Get the values for the credentials you set in the '.env' file
database = environment_variables.get("DATABASE")
server = environment_variables.get("SERVER")
username = environment_variables.get("USERNAME")
password = environment_variables.get("PASSWORD")


connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}"

In [6]:
connection = pyodbc.connect(connection_string)

In [7]:
# Get dataset 1 from sql server 
query = 'SELECT * FROM LP1_startup_funding2020;'

df_2020 = pd.read_sql_query(query, connection)

In [8]:
df_2020.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None

In [9]:
# Get dataset 2 from sql server
query2 = 'SELECT * FROM LP1_startup_funding2021;'

df_2021 = pd.read_sql_query(query2, connection)

In [10]:
df_2021

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019.0,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A
1205,Vahdam,2015.0,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D
1206,Leap Finance,2019.0,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C
1207,CollegeDekho,2015.0,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B
1208,WeRize,2019.0,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A

In [11]:
df_2020.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None

In [12]:
df_2021.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed

In [13]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  1055 non-null   object
 1   Founded        842 non-null    float64
 2   HeadQuarter    961 non-null    object
 3   Sector         1042 non-null   object
 4   What_it_does   1055 non-null   object
 5   Founders       1043 non-null   object
 6   Investor       1017 non-null   object
 7   Amount         801 non-null    float64
 8   Stage          591 non-null    object
 9   column10       2 non-null      object
dtypes: float64(2), object(8)
memory usage: 82.5+ KB

In [14]:
df_2020.shape

(1055, 10)

In [15]:
df_2021.shape

(1209, 9)

In [16]:
# Combine dataset 1 and dataset 2 from sql server
df_data1 = pd.concat([df_2020, df_2021])

# Convert combined dataset (data 1) from sql server to .csv
df_data1.to_csv('combinedData1')

In [17]:
# Combined Dataset (Data 1) from sql server
df = pd.read_csv('combinedData1.csv')

In [18]:
df

,Unnamed: 0,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,NaN,NaN
1,1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,NaN
2,2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,NaN
3,3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,NaN,NaN
4,4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2259,1204,Gigforce,2019.0,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A,NaN
2260,1205,Vahdam,2015.0,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D,NaN
2261,1206,Leap Finance,2019.0,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C,NaN
2262,1207,CollegeDekho,2015.0,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B,NaN
2263,1208,WeRize,2019.0,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A,NaN

In [19]:
# Read data 2 (.csv file)
df_data2 = pd.read_csv(r"C:\Users\ofori\OneDrive\Documents\AzubiAfricaData\LP1_Sojourn\LP1_Sojourn_Azubi\startup_funding2019.csv")

In [20]:
# Combine data 1 and data 2
df_data1_data2 = pd.concat([df_data1,df_data2])
df_data1_data2.head(2)
df_data1_data2.shape

(2353, 13)

In [21]:
# Read data 3 (.csv file) 
df_data3 = pd.read_csv(r"C:\Users\ofori\OneDrive\Documents\AzubiAfricaData\LP1_Sojourn\LP1_Sojourn_Azubi\startup_funding2018.csv")

In [22]:
# Combine data 1, data 2 and data 3
lp1_rawfulldata = pd.concat([df_data1_data2,df_data3])
lp1_rawfulldata.shape
lp1_rawfulldata.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2879 entries, 0 to 525
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  2264 non-null   object
 1   Founded        2110 non-null   float64
 2   HeadQuarter    2239 non-null   object
 3   Sector         2335 non-null   object
 4   What_it_does   2264 non-null   object
 5   Founders       2334 non-null   object
 6   Investor       2253 non-null   object
 7   Amount         2533 non-null   object
 8   Stage          1415 non-null   object
 9   column10       2 non-null      object
 10  Company/Brand  89 non-null     object
 11  What it does   89 non-null     object
 12  Amount($)      89 non-null     object
 13  Company Name   526 non-null    object
 14  Industry       526 non-null    object
 15  Round/Series   526 non-null    object
 16  Location       526 non-null    object
 17  About Company  526 non-null    object
dtypes: float64(1), object(17)
memory usage: 427.4+ KB

In [23]:
# Read 3 combined data set
lp1_rawfulldata.to_csv('lp1_rawfulldata')

In [24]:
lp1_rawfulldata

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10,Company/Brand,What it does,Amount($),Company Name,Industry,Round/Series,Location,About Company
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225000000,NaN,NaN,NaN,NaN,NaN,Udaan,"B2B, Business Development, Internet, Marketplace",Series C,"Bangalore, Karnataka, India","Udaan is a B2B trade platform, designed specif..."
522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,—,NaN,NaN,NaN,NaN,NaN,Happyeasygo Group,"Tourism, Travel",Series A,"Haryana, Haryana, India",HappyEasyGo is an online travel domain.
523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500,NaN,NaN,NaN,NaN,NaN,Mombay,"Food and Beverage, Food Delivery, Internet",Seed,"Mumbai, Maharashtra, India",Mombay is a unique opportunity for housewives ...
524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"₹35,000,000",NaN,NaN,NaN,NaN,NaN,Droni Tech,Information Technology,Seed,"Mumbai, Maharashtra, India",Droni Tech manufacture UAVs and develop softwa...
525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35000000,NaN,NaN,NaN,NaN,NaN,Netmeds,"Biotechnology, Health Care, Pharmaceutical",Series C,"Chennai, Tamil Nadu, India",Welcome to India's most convenient pharmacy!